version: "2.2"

services:
  keycloak:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      TZ: UTC
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
       postgres_keycloak:
         condition: service_healthy
    networks:
      - keycloak_network

  postgres_keycloak:
    image: postgres:15.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pqdata_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      TZ: UTC
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_network
volumes:
  pqdata_keycloak:
networks:
  keycloak_network:
    driver: bridge